### ISSUE TITLE
free algebra not generating what I thought

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#143]
I tried moving my simple app to use freestyle to generate the boilerplate but I get a compile failure. Very simple app (doesn't even do anything yet), fully reproducible in this commit:

https://github.com/fommil/drone-dynamic-agents/commit/3416de2a1c8aec6dc9da275641246cbe3058b383

failure is

```
[error] /home/fommil/Projects/drone-dynamic-agents/src/main/scala/logic.scala:25: type mismatch;
[error]  found   : cats.free.Free[F,(algebra.Drone.WorkQueue, algebra.Drone.WorkActive, List[java.util.UUID])]
[error]  required: cats.free.Free[[β$0$]cats.free.FreeApplicative[F,β$0$],?]
[error]       nodes <- c.getNodes()
[error]             ^
```

It looks like `freestyle` is not generating exactly the same free algebra that the boilerplate is generating. Is that correct?

**Comment by fommil** [comment]
is this because

```
type FreeS[F[_], A] = Free[FreeApplicative[F, ?], A]
```

whereas before I was using `Free[F, A]` ?

**Comment by fommil** [comment]
Update, moving everything to Freestyle (and `FreeS` instead of `Free`) fixes it https://github.com/fommil/drone-dynamic-agents/commit/410cd2c2b168838c2c63348575fda8f6a0de6d6e

It would be useful to explain for the docs to have more description about what `FreeS` is vs `Free[F, ?]`. I still have no idea.

**Comment by raulraja** [comment]
@fommil a bit of what the type alias is explained here http://frees.io/docs/parallelism/ but agreed it needs to be more clear. Basically in order to support Parallelism there is a `FreeApplicative` on top of the regular `F` you'd find in a regular `Free` programs. Free monads as is in `cats.free.Free` can't support parallel operations because a Monad denotes sequential steps where one is not evaluated until the previous one completes regardless of whether you use for comprehensions or not. Introducing an Applicative in a monadic step you gain parallelism because the Applicative allows modeling operations that are not interdependent and therefore may be interpreted in parallel. .

For example in your code you have :
```scala
val ddd = for {
      work <- d.receiveWorkQueue()
      active <- d.receiveActiveWork()
      nodes <- c.getNodes()
    } yield (work, active, nodes)
```
The only reason this code would make sense in a monadic sequence like the one above is if each of the operations where interdependent or they caused side effects that require you to execute those operations in that particular order as declared in that for comprehension. Assuming those functions are pure (no side effects) and are just to get those `work`, `active` and `nodes` values you could instead parallelize them like so:

1. Define your algebra return types to be of type `FreeS.Par[F, A` instead of `FreeS[F, A]`
2. Define `ddd` like this...
```scala
import cats.implicits._
import freestyle.nondeterminism._
val ddd = (d.receiveWorkQueue() |@| d.receiveActiveWork() |@| c.getNodes()).tupled
ddd.exec[Future] // this will run in parallel each of the operations above and join the results.
```

With this new definition without monadic steps in a for comprehension you are saying that you have 3 independent operations. If at the time of interpretation you were to use the `Future` or `Task` non deterministic instances that Freestyle provides your code would run in parallel. The `|@|` is the cats cartesian builder to compose multiple independent operations that join their results once they complete.

The piece of code that introduces non-determinism for `Future` for is here:
https://github.com/47deg/freestyle/blob/master/freestyle/shared/src/main/scala/freestyle/NonDeterminism.scala#L41

Let me know if you have any questions or run into any issues, I'd love to help. Cheers!

**Comment by fommil** [comment]
@raulraja cool, thanks. Argh, I created a fresh ticket at #145 once I figured out what was going on. I do think it would be useful to allow *just* generating the `Free`, not the `FreeS`.

**Comment by raulraja** [comment]
I'll flag the ticket as a feature request and we will consider it when we tackle #53. Amoung our plans which we have started exploring in #93 we may want to be able down the road to support the following generations:
- Final tagless
- Extensible Effects via eff
- cats.free.Free (with and without applicatives)

**Comment by fommil** [comment]
@raulraja excellent, this is doing as you suggest https://github.com/fommil/drone-dynamic-agents/commit/df24cebb36727ad7f2cb7a62113f15ede29096ec

of course, I'm wanting to rewrite this app to be streaming rather than procedural but it's good to see that this would at least improve the parallelisability of the procedural `Free` version of the app.

**Comment by fommil** [comment]
hmm, that said... I'm not 100% sure if the work inside the `map` is now being performed. That'll need some tests.
