### ISSUE TITLE
Replace `cats.data.Coproduct` and `Inject` with iota to improve interpretation performance.

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#254]
https://github.com/47deg/iota championed by @andyscott is a faster impl of coproduct based on an indexed List which yields constant access time regardless of the number of Algebras. Let's get this replaced before 0.1.0!

**Comment by diesalbla** [comment]
Replacing `cats` implementation of `Coproduct` and `Inject` (soon to be named `EitherK`) will also allow us to use non-degenerate _unions_ when composing the algebras.

In `cats 0.9.0` (the version we currently use), the `Inject` data type is sealed and restricted to a set of  instances, which follows the instances from the [_Data types à la Carte_](http://dblp.uni-trier.de/rec/bibtex/journals/jfp/Swierstra08) article. These instances restrict the use of the technique to those cases in which the composition of three or more _algebras_, v.g. `A + B + C + D`, is only possible in a right-associative linear way, i.e. `A + (B+ (C + D))`. 

For `freestyle`, this restriction has affected us in the implementation of the `@module` macro. One feature for this annotation is to allow having _modules_ that use other _modules_, e.g.
```scala
@module trait Ann { val x: X ; val y: Y }
@module trait Bob { val z: Z ; val w: W}
@module trait Carl { val a: Ann ; val b: Bob }
```
When expanding the macro for `Carl`, although we can just define `Carl.Op = Coproduct[Ann.Op, Bob.Op]`, this definition is not usable because we then can not build any instance of `Inject[X.Op, Carl.Op]`, as we would need to _lift_ the operations from `X`. 

Instead, our implementation of the `@module` macro needs to assemble the full list `[X,Y,Z,W]` of all algebras, so as to build `Carl.Op = X.Op + (Y.Op + (Z.Op `W.Op) )`. To do this, it needs to perform the recursive search shown [here](https://github.com/47deg/freestyle/blob/7903863839e0d88a09c3a241f59e43c6f49606fd/freestyle/shared/src/main/scala/freestyle/module.scala#L38). This has several drawbacks: 
* It requires us to use type information in the macros. This is more complex than syntactic transformations, and that may be more difficult to do with scalameta #73.  
* It somehow breaks the _encapsulation_ and structuring of code intended for `@module`, since it goes into the inner components of each `@module`. 
* It hinders composition of operations based on one module. In a case brought yesterday in `gitter`, one may wish to define two processes exclusively in the _lower_ module, that is to say to have expressions of type `FreeS[Ann.Op]` and `FreeS[Bob.Op]`, and lift them together to `FreeS[Carl.Op]`. At present, this is not possible, which makes nested `@module` not too useful. 

Thus, it would be useful if `iota` would make it possible to have _hierarchical_ module composition that would ease implementation and support some of these use cases.
