### ISSUE TITLE
Publish microsite automatically in Travis

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#31]
We should update and publish the site docs under `frees.io` and update the live site automatically when travis builds master successfully. Work in progress in #17

**Comment by javipacheco** [comment]
I have updated the branch in order to publish the site when we merge in master. During my tests, I have published the site for checking the process and you can see the [website online](https://47deg.github.io/freestyle/) now

In the future, the website will be published only when we merge in `master`

I have changed the encrypted file, and now, we have encrypted the `keys.tar` file that it contains `travis-deploy-key` and `secring.gpg`

Currently, the branch has conflicts that must be resolved

@raulraja could you please review? thanks!

@juanpedromoreno thought?
