### ISSUE TITLE
Inject Journal's Logger instance

### ISSUE THREAD

**Issue by pepegar** [47deg/freestyle#47]
I'm not using `freestyle` yet, but it's indeed very appealing.

I have a similar logging algebra in a project of mine, and found it really useful to not instantiate `Logger` directly in the body of the interpreter (https://github.com/47deg/freestyle/blob/master/freestyle-logging/jvm/src/main/scala/io/freestyle/loggingJVM.scala#L14), first compiling to `Kleisli[F, Logger, A]`. It has several benefits, for example, that using your approach it'll take the first `Manifest[C]` from the environment.

I propose something like follows:

```scala
  def LogInterp[F[_] : MonadError[?[_], Throwable]](log: Logger): LogF ~> F = LogInterpK andThen KleisliInterp(log)

  def KleisliInterp[F[_] : MonadError[?[_], Throwable]](log: Logger): Kleisli[F, Logger, ?] ~> F = λ[Kleisli[F, Logger, ?] ~> F](_.run(log))

  def LogInterpK[F[_]](implicit ME: MonadError[F, Throwable]): LogF ~> Kleisli[F, Logger, ?] = new (LogF ~> Kleisli[F, Logger, ?]) {
    def apply[A](logF: LogF[A]): Kleisli[F, Logger, A] = logF match {
      case Debug(message) => Kleisli { log =>
        ME.catchNonFatal(log.debug(message))
      }
      case Info(message) => Kleisli { log =>
        ME.catchNonFatal(log.info(message))
      }
      case Warn(message) => Kleisli { log =>
        ME.catchNonFatal(log.warn(message))
      }
      case Error(message) => Kleisli { log =>
        ME.catchNonFatal(log.error(message))
      }
    }
  }
```

Are you guys open for a PR?

**Comment by raulraja** [comment]
@pepegar thanks so much!. In the spirit of Freestyle implicits based injection... can we have the logger also be an implicit in the interpreter and provide a default instance right in the companion as well? Other than that your suggestions looks great. I don't think we should parameterize to `Kleisli` in this case in the interpreter because we would impose the constrain of all other interpreters to also be on a `Kleisli` or `MonadReader` to defer injection. This is not an issue for small programs or programs with an existing transformer stack for the target `M[_]` since they will most likely already include a reader but if we can leverage implicits to inject the instance we reduce the complexity in the call site from a user point of view.

**Comment by raulraja** [comment]
Also PR are always welcome, thanks for your interest!

**Comment by raulraja** [comment]
Just realized you had piped interpreters so scratch what I said and yes that would be a great approach.

**Comment by pepegar** [comment]
Ok, great! I'll scratch a PR soon :)

**Comment by raulraja** [comment]
We are getting ready for a `0.1.0` first release. If you still want this in we are still on time. Cheers!
