### ISSUE TITLE
free macro removes the previous extends clause

### ISSUE THREAD

**Issue by abdheshkumar** [47deg/freestyle#540]
```scala
trait CassandraAsyncContext{
  trait Quoted[T]{
    def query: String
  }
}
trait Context {
  val context: CassandraAsyncContext
}

@free trait CassandraAlgebra extends Context {
  def runSingle[T(q: context.Quoted[T]): FS[List[T]]
}
```
after macro generation, trait `Context` got removed.

**Comment by diesalbla** [comment]
The cause for this bug is at [this line](https://github.com/frees-io/freestyle/blob/master/modules/core/shared/src/main/scala/freestyle/free/internal/free.scala#L76). Instead of assigning the `pat` parents, it should append them. 

The same error appears in the `@tagless` macro.

**Comment by diesalbla** [comment]
@abdheshkumar I am afraid that the particular example that you wrote in the code would not work with `@free`, but not just because of `@free` removing the `extends Context` clause. 

The `@free` generates an `Op` ADT which is in an `object`, so it does not have `context` in scope. 
If you used a non-path-dependent type, though, it would work.
